@extends('layouts.app')

@section('page_title', 'WhatsApp Configuration')

@section('content')
    <div class="container-fluid py-2">
        <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><p class="text-muted mb-1">Platform administration</p><h1 class="h3 fw-bold mb-1">WhatsApp Cloud API</h1><p class="text-muted mb-0">Manage the {{ $platformSettings['settings']->product_name }}-owned shared connection used by workspaces that select the shared architecture.</p></div><span class="badge text-bg-primary align-self-center"><i class="fa-solid fa-shield-halved me-1"></i> Platform management</span></div>
        @foreach (['success' => 'success', 'error' => 'danger'] as $key => $class) @if (session($key))<div class="alert alert-{{ $class }}" role="alert">{{ session($key) }}</div>@endif @endforeach
        @if ($errors->any())<div class="alert alert-danger" role="alert"><ul class="mb-0">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <div class="row g-4">
            <div class="col-xl-7">
                <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4">
                    <div class="d-flex justify-content-between gap-3 mb-3"><div><h2 class="h5 fw-bold mb-1">Shared {{ $platformSettings['settings']->product_name }} connection</h2><p class="text-muted small mb-0">All shared-architecture workspaces send through this number.</p></div><span class="badge text-bg-{{ $connection?->status === 'connected' ? 'success' : 'secondary' }} align-self-start">{{ str($connection?->status ?? 'not_connected')->replace('_', ' ')->title() }}</span></div>
                    <form method="POST" action="{{ route('platform.whatsapp.update') }}">@csrf @method('PUT')<div class="row g-3"><div class="col-md-6"><label class="form-label">Business portfolio ID</label><input name="business_portfolio_id" value="{{ old('business_portfolio_id', $connection?->business_portfolio_id ?? config('services.whatsapp.business_portfolio_id')) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">WABA ID</label><input name="waba_id" value="{{ old('waba_id', $connection?->waba_id ?? config('services.whatsapp.shared_waba_id')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Phone number ID</label><input name="phone_number_id" value="{{ old('phone_number_id', $connection?->phone_number_id ?? config('services.whatsapp.shared_phone_number_id')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Display phone number</label><input name="display_phone_number" value="{{ old('display_phone_number', $connection?->display_phone_number ?? config('services.whatsapp.shared_display_phone_number')) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">Verified business name</label><input name="verified_name" value="{{ old('verified_name', $connection?->verified_name ?? config('services.whatsapp.shared_verified_name')) }}" class="form-control"></div><div class="col-md-6"><label class="form-label">System/user access token</label><input type="password" name="access_token" class="form-control" autocomplete="new-password" placeholder="{{ $connection?->exists ? 'Leave blank to keep current token' : 'Required unless supplied by .env' }}"></div></div><button class="btn btn-primary mt-3" type="submit"><i class="fa-solid fa-floppy-disk me-1"></i> Save and verify shared connection</button></form>
                    @if ($connection?->exists)<form method="POST" action="{{ route('platform.whatsapp.disconnect') }}" class="mt-3" data-lifecycle-confirm data-lifecycle-title="Disconnect shared WhatsApp?" data-lifecycle-text="All workspaces using the shared architecture will stop sending WhatsApp reminders." data-lifecycle-confirm-text="Disconnect">@csrf<button class="btn btn-outline-danger btn-sm" type="submit"><i class="fa-solid fa-unlink me-1"></i> Disconnect shared connection</button></form>@endif
                </div></div>

                <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 fw-bold mb-1">Shared reminder templates</h2><p class="text-muted small mb-3">These mappings apply to every workspace that selects the shared architecture.</p>@foreach ($templateTypes as $type) @php($template = $templates->firstWhere('type', $type))<form method="POST" action="{{ route('platform.whatsapp.templates.update') }}" class="border rounded p-3 mb-3">@csrf @method('PUT')<input type="hidden" name="type" value="{{ $type }}"><div class="fw-semibold mb-2">{{ str($type)->replace('_', ' ')->title() }}</div><div class="row g-2"><div class="col-md-7"><input name="template_name" value="{{ old('template_name', $template?->template_name) }}" class="form-control form-control-sm" placeholder="approved_template_name" required></div><div class="col-md-5"><input name="language_code" value="{{ old('language_code', $template?->language_code ?? 'en_US') }}" class="form-control form-control-sm" required></div><div class="col-12"><input name="body" value="{{ old('body', $template?->body) }}" class="form-control form-control-sm" placeholder="Optional variable map"></div></div><div class="form-check mt-2"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="shared-template-{{ $type }}" @checked($template?->is_active ?? true)><label class="form-check-label small" for="shared-template-{{ $type }}">Use this approved template</label></div><button class="btn btn-sm btn-outline-primary mt-2" type="submit">Save mapping</button></form>@endforeach</div></div>
            </div>
            <div class="col-xl-5">
                    <div class="card border-0 shadow-sm mb-4"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Tenant connections</h2><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Workspace</th><th>Status</th><th>Phone</th><th></th></tr></thead><tbody>@forelse ($tenantConnections as $tenantConnection)<tr><td>{{ $tenantConnection->workspace?->name ?? 'Deleted workspace' }}</td><td><span class="badge text-bg-{{ $tenantConnection->status === 'connected' ? 'success' : 'secondary' }}">{{ str($tenantConnection->status)->replace('_', ' ')->title() }}</span></td><td class="small">{{ $tenantConnection->display_phone_number ?: '—' }}</td><td class="text-end">@if ($tenantConnection->workspace)<form method="POST" action="{{ route('platform.whatsapp.tenant.disconnect', $tenantConnection->workspace) }}" data-lifecycle-confirm data-lifecycle-title="Disconnect tenant WhatsApp?" data-lifecycle-text="This tenant will stop sending through its connected WhatsApp number." data-lifecycle-confirm-text="Disconnect">@csrf<button class="btn btn-sm btn-outline-danger" type="submit" title="Disconnect"><i class="fa-solid fa-unlink"></i></button></form>@endif</td></tr>@empty<tr><td colspan="4" class="text-muted small">No tenant connections have been configured.</td></tr>@endforelse</tbody></table></div>{{ $tenantConnections->links() }}</div></div>
                <div class="card border-0 shadow-sm"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Connection audit</h2>@forelse ($audits as $audit)<div class="border-bottom pb-3 mb-3"><div class="small fw-semibold">{{ str($audit->event)->replace('_', ' ')->title() }}</div><div class="small text-muted">{{ $audit->actor?->name ?? 'System' }} · {{ $audit->created_at->format('M j, Y H:i') }}</div><div class="small text-muted">{{ count($audit->changes ?? []) }} field(s) changed</div></div>@empty<p class="small text-muted mb-0">No shared connection changes have been audited yet.</p>@endforelse</div></div>
            </div>
        </div>
    </div>
@endsection
