@extends('layouts.app')

@section('page_title', 'Moderate Testimonial')

@section('content')
    <div class="container-fluid px-0">
        <div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4"><div><p class="text-muted mb-1">{{ $testimonial->workspace?->name }}</p><h1 class="h3 fw-bold mb-1">{{ $testimonial->display_name }}</h1>@include('testimonials._status_badge', ['testimonial' => $testimonial])</div><a href="{{ route('platform.testimonials.index') }}" class="btn btn-outline-secondary">Back to queue</a></div>
        <div class="row g-4">
            <div class="col-12 col-xl-8"><div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4">
                <div class="d-flex align-items-center gap-3 mb-4">
                    @if ($testimonial->image_url)<img src="{{ $testimonial->image_url }}" alt="{{ $testimonial->display_name }}" class="rounded-circle object-fit-cover" style="width: 88px; height: 88px;">@else<span class="rounded-circle bg-light text-primary d-inline-flex align-items-center justify-content-center" style="width: 88px; height: 88px;"><i class="fa-solid fa-user fs-2"></i></span>@endif
                    <div><h2 class="h5 mb-1">{{ $testimonial->display_name }}</h2><p class="text-muted mb-1">{{ $testimonial->job_title }}{{ $testimonial->job_title && $testimonial->business_name ? ' · ' : '' }}{{ $testimonial->business_name }}</p><div class="text-warning" aria-label="{{ $testimonial->rating }} out of 5 stars">{{ str_repeat('★', $testimonial->rating) }} <span class="text-muted small">{{ $testimonial->rating }}/5</span></div></div>
                </div>
                <blockquote class="blockquote mb-0"><p class="fs-5">{!! nl2br(e($testimonial->content)) !!}</p></blockquote>
            </div></div></div>
            <div class="col-12 col-xl-4"><div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-4">
                <h2 class="h5 fw-bold mb-3">Consent and history</h2><dl class="row small mb-0"><dt class="col-6 text-muted">Consent</dt><dd class="col-6 text-end">@if($testimonial->consent_confirmed)<span class="text-success">Confirmed</span>@else<span class="text-danger">Missing</span>@endif</dd><dt class="col-6 text-muted">Consented by</dt><dd class="col-6 text-end">{{ $testimonial->consenter?->name ?: 'Unknown' }}</dd><dt class="col-6 text-muted">Submitted</dt><dd class="col-6 text-end">{{ $testimonial->submitted_at?->format('M j, Y H:i') ?: 'Not submitted' }}</dd><dt class="col-6 text-muted">Reviewed by</dt><dd class="col-6 text-end">{{ $testimonial->reviewer?->name ?: 'Not reviewed' }}</dd><dt class="col-6 text-muted">Reviewed</dt><dd class="col-6 text-end">{{ $testimonial->reviewed_at?->format('M j, Y H:i') ?: 'Not reviewed' }}</dd></dl>
            </div></div>
            @if ($testimonial->status === 'pending_review')<div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Moderation decision</h2><div class="d-flex flex-wrap gap-2 mb-3"><form method="POST" action="{{ route('platform.testimonials.approve', $testimonial) }}" data-lifecycle-confirm data-lifecycle-title="Approve testimonial?" data-lifecycle-text="This testimonial will be eligible for publication." data-lifecycle-confirm-text="Approve">@csrf<button type="submit" class="btn btn-success">Approve</button></form><form method="POST" action="{{ route('platform.testimonials.reject', $testimonial) }}" data-lifecycle-confirm data-lifecycle-title="Reject testimonial?" data-lifecycle-text="The workspace will be notified with the rejection reason." data-lifecycle-confirm-text="Reject">@csrf<div class="input-group"><input type="text" name="rejection_reason" class="form-control" placeholder="Rejection reason" aria-label="Rejection reason" required minlength="5" maxlength="2000"><button type="submit" class="btn btn-outline-danger">Reject</button></div></form></div></div></div>@endif
            @if (in_array($testimonial->status, ['approved', 'rejected', 'unpublished'], true))<div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Correction workflow</h2><form method="POST" action="{{ route('platform.testimonials.return-to-draft', $testimonial) }}" data-lifecycle-confirm data-lifecycle-title="Return to draft?" data-lifecycle-text="The workspace will be notified and can correct this testimonial." data-lifecycle-confirm-text="Return to draft">@csrf<label for="return-reason" class="form-label small text-muted">Correction note</label><textarea id="return-reason" name="reason" rows="2" class="form-control mb-2" maxlength="2000" placeholder="What should the workspace correct?"></textarea><button type="submit" class="btn btn-outline-warning">Return to draft</button></form></div></div>@endif
            @if ($testimonial->status === 'approved' || $testimonial->status === 'published')<div class="card border-0 shadow-sm rounded-4"><div class="card-body p-4"><h2 class="h5 fw-bold mb-3">Homepage presentation</h2><form method="POST" action="{{ route('platform.testimonials.presentation', $testimonial) }}">@csrf @method('PATCH')<div class="form-check mb-3"><input id="featured" type="checkbox" name="featured" value="1" class="form-check-input" @checked($testimonial->featured)><label for="featured" class="form-check-label">Feature this testimonial</label></div><label for="display-order" class="form-label">Display order</label><input id="display-order" type="number" name="display_order" value="{{ $testimonial->display_order }}" min="0" max="9999" class="form-control mb-3" required><button type="submit" class="btn btn-outline-primary">Save presentation</button></form>@if($testimonial->status === 'approved')<form method="POST" action="{{ route('platform.testimonials.publish', $testimonial) }}" class="mt-3" data-lifecycle-confirm data-lifecycle-title="Publish testimonial?" data-lifecycle-text="This testimonial will be visible on the public IDT homepage." data-lifecycle-confirm-text="Publish">@csrf<button type="submit" class="btn btn-primary w-100">Publish testimonial</button></form>@else<form method="POST" action="{{ route('platform.testimonials.unpublish', $testimonial) }}" class="mt-3" data-lifecycle-confirm data-lifecycle-title="Unpublish testimonial?" data-lifecycle-text="This testimonial will be removed from the public IDT homepage." data-lifecycle-confirm-text="Unpublish">@csrf<button type="submit" class="btn btn-outline-danger w-100">Unpublish testimonial</button></form>@endif</div></div>@endif
            @if ($testimonial->status === 'rejected' && $testimonial->rejection_reason)<div class="alert alert-danger mt-4 mb-0"><strong>Rejection reason:</strong> {{ $testimonial->rejection_reason }}</div>@endif
            </div>
        </div>
    </div>
@endsection
